version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-ishiko-cpp:0.43.0
    steps:
      - run: 
          name: "Set NEMU_CPP_ROOT environment variable and create workspace directory"
          command: mkdir -p /workspace/projects/nemu/cpp && echo 'export NEMU_CPP_ROOT="/workspace/projects/nemu/cpp"' >> $BASH_ENV
      - checkout:
          path: /workspace/projects/nemu/cpp/core
      - run:
          name: Build Core
          command: cd /workspace/projects/nemu/cpp/core/build-files/gnumake && make
      - run:
          name: "Test: Core"
          command: cd /workspace/projects/nemu/cpp/core/tests/build-files/gnumake && make && ./NemuCoreTests
workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
